export default {
    LOG_IN: "LOG_IN",
    LOG_IN_FAILED: "LOG_IN_FAILED",
    LOG_IN_LOADING: "LOG_IN_LOADING",
    LOG_IN_SUCCESS: "LOG_IN_SUCCESS",

    SIGN_UP: "SIGN_UP",
    SIGN_UP_FAILED: "SIGN_UP_FAILED",
    SIGN_UP_LOADING: "SIGN_UP_LOADING",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",

    SIGN_OUT: "SIGN_OUT",
    SIGN_OUT_FAILED: "SIGN_OUT_FAILED",
    SIGN_OUT_LOADING: "SIGN_OUT_LOADING",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
}